import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const SUPABASE_URL='https://jfmzukwfymuwamsldojx.supabase.co';
const SUPABASE_KEY='sb_publishable_ULWoIXtScA85GN58Tg4gkA_3o0PJvdQ';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const games=[
 ['neon-arena','Neon Arena','Arcade','⚡','Sobreviva aos inimigos neon e faça a maior pontuação.'],
 ['space-shooter','Space Shooter','Ação','🚀','Destrua asteroides e sobreviva o máximo possível.'],
 ['snake-arena','Snake Arena','Arcade','🐍','Colete energia, cresça e não bata em si mesmo.'],
 ['dungeon-run','Dungeon Run','Aventura','⚔️','Avance pela masmorra, derrote monstros e sobreviva.'],
 ['tower-defense','Tower Defense','Estratégia','🏰','Defenda sua base contra ondas de inimigos.'],
 ['pixel-racing','Pixel Racing','Corrida','🏎️','Desvie do trânsito e alcance a maior velocidade.'],
 ['2048-battle','2048 Battle','Puzzle','🔢','Combine números e tente chegar ao 2048.'],
 ['memory-master','Memory Master','Puzzle','🧠','Encontre todos os pares no menor tempo.'],
 ['flappy-rush','Flappy Rush','Arcade','🐤','Passe pelos obstáculos sem tocar neles.'],
 ['clicker-empire','Clicker Empire','Casual','💰','Clique, acumule moedas e construa seu império.']
];
let currentUser=null,currentGame=null,gameCleanup=()=>{};
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function renderGames(filter=''){ $('#gameGrid').innerHTML=games.filter(g=>(g[1]+g[2]+g[4]).toLowerCase().includes(filter.toLowerCase())).map(g=>`<article class="gameCard" data-game="${g[0]}"><div class="gameIcon">${g[3]}</div><span class="tag">${g[2]}</span><h3>${g[1]}</h3><p class="muted">${g[4]}</p></article>`).join('')||'<p class="muted">Nenhum jogo encontrado.</p>'; document.querySelectorAll('.gameCard').forEach(c=>c.onclick=()=>openGame(c.dataset.game)); }
async function loadPublicData(){
 const {data:ach}=await supabase.from('achievements').select('name,description,xp_reward,coin_reward').limit(6);
 $('#missionList').innerHTML=(ach?.length?ach:[{name:'Primeira partida',description:'Jogue qualquer jogo.',xp_reward:25,coin_reward:50},{name:'Caçador de recordes',description:'Supere seu recorde.',xp_reward:50,coin_reward:100},{name:'Maratonista',description:'Jogue 5 partidas.',xp_reward:100,coin_reward:200}]).map(a=>`<div class="card"><h3>🏆 ${esc(a.name)}</h3><p class="muted">${esc(a.description)}</p><small>+${a.xp_reward} XP • +${a.coin_reward} moedas</small></div>`).join('');
 const {data:shop}=await supabase.from('shop_items').select('name,description,item_type,price_coins,price_gems,rarity').limit(8);
 $('#shopList').innerHTML=(shop?.length?shop:[{name:'Avatar Neon',description:'Visual padrão NexPlay.',item_type:'avatar',price_coins:250,price_gems:0,rarity:'rare'},{name:'Skin Cyber',description:'Skin futurista.',item_type:'skin',price_coins:800,price_gems:0,rarity:'epic'},{name:'Título: Veterano',description:'Mostre sua experiência.',item_type:'title',price_coins:1200,price_gems:20,rarity:'legendary'}]).map(i=>`<div class="card"><span class="tag">${i.rarity}</span><h3>✨ ${esc(i.name)}</h3><p class="muted">${esc(i.description)}</p><b>${i.price_coins?i.price_coins+' moedas':''}${i.price_coins&&i.price_gems?' • ':''}${i.price_gems?i.price_gems+' gemas':''}</b></div>`).join('');
}
async function loadRanking(){const {data}=await supabase.from('game_history').select('score,user_id').order('score',{ascending:false}).limit(10);if(!data?.length){$('#rankingList').innerHTML='<p class="muted">Ainda não há partidas registradas. Seja o primeiro.</p>';return}$('#rankingList').innerHTML=data.map((r,i)=>`<div style="display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #ffffff0d"><b>#${i+1}</b><span>${r.user_id.slice(0,8)}...</span><strong>${r.score}</strong></div>`).join('')}
async function loadProfile(){if(!currentUser)return;const {data}=await supabase.from('profiles').select('display_name,username,level,xp,coins,gems').eq('id',currentUser.id).maybeSingle();if(!data)return;const old=$('#profilePanel');if(old)old.remove();const p=document.createElement('div');p.id='profilePanel';p.className='panel';p.style.cssText='position:fixed;right:18px;top:78px;z-index:30;width:260px';p.innerHTML=`<b>${esc(data.display_name)}</b><div class="muted">@${esc(data.username)}</div><hr><div>Nível <strong>${data.level}</strong></div><div>XP <strong>${data.xp}</strong></div><div>🪙 ${data.coins} • 💎 ${data.gems}</div>`;document.body.appendChild(p);setTimeout(()=>p.remove(),5000)}
function userUI(){if(currentUser){$('#userBox').innerHTML=`<button class="btn" id="profileBtn">Perfil</button><button class="btn" id="logoutBtn">Sair</button>`;$('#logoutBtn').onclick=()=>supabase.auth.signOut();$('#profileBtn').onclick=loadProfile}else{$('#userBox').innerHTML='<button class="btn" id="loginBtn">Entrar</button>';$('#loginBtn').onclick=()=>$('#authModal').classList.remove('hidden')}}
async function ensureProfile(){if(!currentUser)return;const {data}=await supabase.from('profiles').select('id').eq('id',currentUser.id).maybeSingle();if(!data){const base=(currentUser.email||'player').split('@')[0].replace(/[^a-zA-Z0-9_]/g,'').slice(0,20)||'player';await supabase.from('profiles').insert({id:currentUser.id,username:base+'_'+Math.floor(Math.random()*9999),display_name:base,level:1,xp:0,coins:0,gems:0})}}
async function recordScore(score,result='finished',duration=0){if(!currentUser||!currentGame)return;const g=games.find(x=>x[0]===currentGame);const {data:game}=await supabase.from('games').select('id').eq('slug',g[0]).maybeSingle();if(!game)return;const safe=Math.max(0,Math.floor(score));const xp=Math.min(1000,Math.floor(safe/10));await supabase.from('game_sessions').insert({user_id:currentUser.id,game_id:game.id,score:safe,duration_seconds:Math.round(duration),result});await supabase.from('game_history').insert({user_id:currentUser.id,game_id:game.id,score:safe,xp_earned:xp});const {data:p}=await supabase.from('profiles').select('xp,coins,level').eq('id',currentUser.id).maybeSingle();if(p){const newXp=(p.xp||0)+xp;const newLevel=Math.max(1,Math.floor(newXp/1000)+1);await supabase.from('profiles').update({xp:newXp,coins:(p.coins||0)+Math.floor(xp/2),level:newLevel}).eq('id',currentUser.id)}await loadRanking()}
function openGame(slug){currentGame=slug;const g=games.find(x=>x[0]===slug);$('#modalTitle').textContent=g[1];$('#modalCategory').textContent=g[2];$('#gameModal').classList.remove('hidden');$('#scoreText').textContent='Pontuação: 0';gameCleanup();gameCleanup=buildGame(slug)}
function closeGame(){gameCleanup();gameCleanup=()=>{};$('#gameModal').classList.add('hidden')}
function buildGame(slug){const area=$('#gameArea');area.innerHTML='';const canvas=document.createElement('canvas');canvas.width=760;canvas.height=430;area.appendChild(canvas);const ctx=canvas.getContext('2d');let raf=0,score=0,start=performance.now(),alive=true,last=performance.now();const keys={};const down=e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space')keys.space=true},up=e=>{keys[e.key.toLowerCase()]=false;if(e.code==='Space')keys.space=false};addEventListener('keydown',down);addEventListener('keyup',up);const finish=()=>{if(!alive)return;alive=false;cancelAnimationFrame(raf);recordScore(Math.floor(score),'finished',(performance.now()-start)/1000)};const text=(t,x,y,size=20)=>{ctx.fillStyle='#fff';ctx.font=`800 ${size}px system-ui`;ctx.fillText(t,x,y)};
 if(slug==='clicker-empire'){let coins=0;area.innerHTML='<button class="btn primary" id="clickEmpire" style="font-size:35px;padding:45px">💰 CLIQUE</button><p id="clickScore">0 moedas</p>';const b=$('#clickEmpire');b.onclick=()=>{coins++;score=coins;$('#clickScore').textContent=coins+' moedas';$('#scoreText').textContent='Pontuação: '+coins};return()=>{b.onclick=null;if(!alive)return;alive=false;recordScore(coins,'finished',(performance.now()-start)/1000)}}
 if(slug==='memory-master'){const vals=[1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8].sort(()=>Math.random()-.5);let open=[],matched=0,locked=false;area.innerHTML='<div id="memory" style="display:grid;grid-template-columns:repeat(4,70px);gap:9px"></div>';const m=$('#memory');vals.forEach((v,i)=>{const b=document.createElement('button');b.className='btn';b.style.height='70px';b.textContent='?';b.onclick=()=>{if(locked||open.includes(i)||b.dataset.ok)return;b.textContent=v;open.push(i);if(open.length===2){locked=true;setTimeout(()=>{const[a,z]=open;if(vals[a]===vals[z]){m.children[a].dataset.ok=1;m.children[z].dataset.ok=1;matched+=2;score+=100}else{m.children[a].textContent='?';m.children[z].textContent='?'}open=[];locked=false;$('#scoreText').textContent='Pontuação: '+score;if(matched===vals.length)finish()},450)}};m.appendChild(b)});return()=>{if(alive)finish()}}
 if(slug==='2048-battle'){let board=Array(16).fill(0);const spawn=()=>{const e=board.map((v,i)=>v?null:i).filter(v=>v!==null);if(e.length)board[e[Math.floor(Math.random()*e.length)]]=Math.random()<.9?2:4};spawn();spawn();const draw=()=>{ctx.clearRect(0,0,760,430);for(let i=0;i<16;i++){const x=160+(i%4)*90,y=35+Math.floor(i/4)*90;ctx.fillStyle='#151d32';ctx.fillRect(x,y,78,78);if(board[i])text(board[i],x+25,y+48,24)}text('Use as setas',300,420,16);raf=requestAnimationFrame(draw)};const move=e=>{const k=e.key.toLowerCase();if(!['arrowleft','arrowright','arrowup','arrowdown'].includes(k))return;e.preventDefault();const before=board.join(',');let rows=[];if(k==='arrowleft'||k==='arrowright')for(let r=0;r<4;r++)rows.push(board.slice(r*4,r*4+4));else for(let c=0;c<4;c++)rows.push([board[c],board[c+4],board[c+8],board[c+12]]);rows=rows.map(row=>{if(k==='arrowright'||k==='arrowdown')row.reverse();row=row.filter(Boolean);for(let i=0;i<row.length-1;i++)if(row[i]===row[i+1]){row[i]*=2;score+=row[i];row.splice(i+1,1)}while(row.length<4)row.push(0);if(k==='arrowright'||k==='arrowdown')row.reverse();return row});if(k==='arrowleft'||k==='arrowright')board=rows.flat();else{board=Array(16).fill(0);rows.forEach((row,c)=>row.forEach((v,r)=>board[r*4+c]=v))}if(board.join(',')!==before)spawn();$('#scoreText').textContent='Pontuação: '+score;if(board.includes(2048))finish()};addEventListener('keydown',move);draw();return()=>{removeEventListener('keydown',move);cancelAnimationFrame(raf);if(alive)finish()}}
 // Neon Arena / Space Shooter / Snake Arena / Dungeon Run / Tower Defense / Pixel Racing / Flappy Rush
 const mode=slug;let p={x:canvas.width/2-15,y:canvas.height-60,w:30,h:30,vx:0,vy:0};let objects=[],spawnTimer=0,shoots=[],cooldown=0,wave=1,health=3,angle=0;
 const pointer=e=>{const r=canvas.getBoundingClientRect();p.x=(e.clientX-r.left)*(canvas.width/r.width)-p.w/2};canvas.addEventListener('pointermove',pointer);
 const fire=()=>{if(mode==='space-shooter'&&cooldown<=0){shoots.push({x:p.x+p.w/2-3,y:p.y,w:6,h:16,v:-520});cooldown=.22}};
 const click=e=>{if(e.code==='Space'||e.key.toLowerCase()==='j')fire()};addEventListener('keydown',click);
 const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
 const loop=t=>{if(!alive)return;const dt=Math.min(.035,(t-last)/1000||0);last=t;spawnTimer-=dt;cooldown-=dt;
   if(mode==='snake-arena'){p.vx=((keys.arrowright||keys.d)?1:(keys.arrowleft||keys.a)?-1:0)*240;p.vy=((keys.arrowdown||keys.s)?1:(keys.arrowup||keys.w)?-1:0)*240;p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=Math.max(0,Math.min(canvas.width-p.w,p.x));p.y=Math.max(0,Math.min(canvas.height-p.h,p.y))}else if(mode==='flappy-rush'){p.vy=(p.vy||0)+900*dt;if(keys.space){p.vy=-340;keys.space=false}p.y+=p.vy*dt}else{if(keys.arrowleft||keys.a)p.x-=320*dt;if(keys.arrowright||keys.d)p.x+=320*dt;p.x=Math.max(0,Math.min(canvas.width-p.w,p.x));p.y=canvas.height-60}
   if(spawnTimer<=0){spawnTimer=mode==='space-shooter'?.32:mode==='tower-defense'?.7:.55;const type=Math.random()<.16?'bonus':'enemy';objects.push({x:Math.random()*(canvas.width-28),y:mode==='flappy-rush'?Math.random()*330:-30,w:28,h:28,v:mode==='pixel-racing'?220+wave*8:110+Math.random()*150,type});}
   if(mode==='space-shooter'){fire();shoots.forEach(s=>s.y+=s.v*dt);shoots=shoots.filter(s=>s.y>-30);for(const s of shoots)for(const o of objects)if(hit(s,o)){o.y=9999;s.y=-99;score+=20}}
   objects.forEach(o=>{o.y+=o.v*dt});objects=objects.filter(o=>o.y<canvas.height+50&&o.y>-80);
   for(const o of objects)if(hit(p,o)){if(o.type==='bonus'){score+=50;o.y=9999}else if(mode==='tower-defense'){health--;o.y=9999;if(health<=0)finish()}else{finish()}}
   if(mode==='snake-arena'){score+=dt*3}else if(mode==='dungeon-run'){score+=dt*2;wave=1+Math.floor(score/100)}else if(mode==='tower-defense'){score+=dt*4;wave=1+Math.floor(score/40)}else score+=dt;
   if(mode==='flappy-rush'&&(p.y<0||p.y+p.h>canvas.height))finish();
   ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#050811';ctx.fillRect(0,0,canvas.width,canvas.height);
   text(mode==='space-shooter'?'🚀':mode==='snake-arena'?'🐍':mode==='dungeon-run'?'⚔️':mode==='tower-defense'?'🏰':mode==='pixel-racing'?'🏎️':mode==='flappy-rush'?'🐤':'⚡',p.x,p.y+25,24);
   objects.forEach(o=>text(o.type==='bonus'?'✦':'●',o.x,o.y+22,22));shoots.forEach(s=>text('│',s.x,s.y,18));
   text(`HP: ${health}`,18,28,14);text(`Wave: ${wave}`,18,48,14);$('#scoreText').textContent='Pontuação: '+Math.floor(score);raf=requestAnimationFrame(loop)};
 raf=requestAnimationFrame(loop);
 return()=>{if(!alive)return;alive=false;cancelAnimationFrame(raf);canvas.removeEventListener('pointermove',pointer);removeEventListener('keydown',click);recordScore(Math.floor(score),'finished',(performance.now()-start)/1000)};
}
$('#search').oninput=e=>renderGames(e.target.value);$('#closeGame').onclick=closeGame;$('#gameModal').onclick=e=>{if(e.target.id==='gameModal')closeGame()};$('#randomBtn').onclick=()=>openGame(games[Math.floor(Math.random()*games.length)][0]);$('#closeAuth').onclick=()=>$('#authModal').classList.add('hidden');let signUp=false;$('#toggleAuth').onclick=()=>{signUp=!signUp;$('#authTitle').textContent=signUp?'Criar conta':'Entrar na NexPlay';$('#authSubmit').textContent=signUp?'Cadastrar':'Entrar';$('#username').style.display=signUp?'block':'none'};$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#email').value,password=$('#password').value;let r;if(signUp)r=await supabase.auth.signUp({email,password,data:{display_name:$('#username').value}});else r=await supabase.auth.signInWithPassword({email,password});if(r.error){$('#authMsg').textContent=r.error.message;return}$('#authMsg').textContent=signUp?'Conta criada. Verifique seu e-mail se necessário.':'Entrando...';$('#authModal').classList.add('hidden')};supabase.auth.onAuthStateChange(async(_,session)=>{currentUser=session?.user||null;if(currentUser)await ensureProfile();userUI()});renderGames();loadPublicData();loadRanking();userUI();